image: "gradle:5.1-jdk8"
stages:
  - build
  - test
  - allure
  - deploy

.download_history: &download_history
  after_script:
    - mkdir backup && cd backup
    - ${CI_PROJECT_DIR}/history.sh
    - (unzip report.zip) || true
    - ls
    - cd ../
    - ls
    - (cp -r backup/report/results/ allure-report) || true
    - .allure/allure-2.8.1/bin/allure generate allure-report/results -o report

.test_template: &test_template
  allow_failure: true
  stage: test
  script:
    - ./gradlew runTests
  artifacts:
    when: always
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - ./report/*
    expire_in: 7 days

build:
  stage: build
  script:
    - ./gradlew clean build

web_tests:
  stage: test
  image: krishnanandb/chromeheadless
  <<: *test_template
  <<: *download_history

pages:
  stage: deploy
  when: always
  dependencies:
    - web_tests
  script:
    - mv report/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master