image: "gradle:5.1-jdk8"
stages:
  - build
  - test
  - allure
  - deploy

.download_history: &download_history
  after_script:
    - apt-get install -y unzip
    - mkdir backup && cd backup || true
    - "curl --location --output report.zip --request GET \"https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/jobs/artifacts/master/download?job=pages\" --header \"Authorization: Bearer ${CI_DEPLOY_TOKEN}\" || true"
    - (unzip report.zip) || true
    - cd ../
    - (cp -r backup/public/history/ allure-results/history) || true

.test_template: &test_template
  allow_failure: true
  stage: test
  script:
    - ./gradlew runTests
  artifacts:
    when: always
    paths:
      - allure-results/

build:
  stage: build
  script:
    - ./gradlew clean build

web_tests:
  stage: test
  image: krishnanandb/chromeheadless
  <<: *test_template
  <<: *download_history

allure_report:
  stage: allure
  when: always
  dependencies:
    - web_tests
  script:
    - gradle allureReport #change allure command specific to your framework
  artifacts:
    when: always
    paths:
      - allure-report/
      - allure-results/
  only:
    - master
pages:
  stage: deploy
  when: always
  dependencies:
    - allure_report
  script:
    - mv allure-report/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master