image: "gradle:5.1-jdk8"
stages:
  - build
  - unit
  - test
  - allure
  - deploy

.download_history: &download_history
  after_script:
    - mkdir backup && cd backup
    - "curl --location --output report.zip --request GET \"https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/jobs/artifacts/master/download?job=pages\" --header \"Authorization: Bearer ${CI_DEPLOY_TOKEN}\" || true"
    - ls
    - cd ../
    - ls
    - (cp -r backup/report/results/ allure-report/results) || true
    - ./gradlew allureReport

.test_template: &test_template
  allow_failure: true
  stage: test
  script:
    - ./gradlew $TASK -DslackNotif=true
  artifacts:
    when: always
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - ./allure-report/ui/*
      - logs/
    expire_in: 14 days

build:
  stage: build
  script:
    - ./gradlew clean build

web_tests:
  stage: test
  variables:
    TASK: runWebTests
  image: krishnanandb/chromeheadless
  <<: *test_template
  <<: *download_history

api_tests:
  stage: test
  variables:
    TASK: runApiTests
  <<: *test_template
  <<: *download_history

db_tests:
  stage: test
  variables:
    TASK: runDBTests
  <<: *test_template
  <<: *download_history

pages:
  stage: deploy
  when: always
  dependencies:
    - web_tests
  script:
    - mv report/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master